matchMode = {"CLASSIC": "Classic","ODIN": "Dominion/Crystal","ARAM": "ARAM","TUTORIAL": "Tutorial","ONEFORALL": "One","ASCENSION": "Ascension","FIRSTBLOOD": "Snowdown","KINGPORO": "King","SIEGE": "Nexus"}

#queueType = {'CUSTOM': 'CUSTOM', 'NORMAL_5x5_BLIND': 'NORMAL_5x5_BLIND', 'RANKED_SOLO_5x5': 'RANKED_SOLO_5x5', 'RANKED_PREMADE_5x5': 'RANKED_PREMADE_5x5', 'BOT_5x5': 'BOT_5x5', 'NORMAL_3x3': 'NORMAL_3x3', 'RANKED_PREMADE_3x3': 'RANKED_PREMADE_3x3', 'NORMAL_5x5_DRAFT': 'NORMAL_5x5_DRAFT', 'ODIN_5x5_BLIND': 'ODIN_5x5_BLIND', 'ODIN_5x5_DRAFT': 'ODIN_5x5_DRAFT', 'BOT_ODIN_5x5': 'BOT_ODIN_5x5', 'BOT_5x5_INTRO': 'BOT_5x5_INTRO', 'BOT_5x5_BEGINNER': 'BOT_5x5_BEGINNER', 'BOT_5x5_INTERMEDIATE': 'BOT_5x5_INTERMEDIATE', 'RANKED_TEAM_3x3': 'RANKED_TEAM_3x3', 'RANKED_TEAM_5x5': 'RANKED_TEAM_5x5', 'BOT_TT_3x3': 'BOT_TT_3x3', 'GROUP_FINDER_5x5': 'GROUP_FINDER_5x5', 'ARAM_5x5': 'ARAM_5x5', 'ONEFORALL_5x5': 'ONEFORALL_5x5', 'FIRSTBLOOD_1x1': 'FIRSTBLOOD_1x1', 'FIRSTBLOOD_2x2': 'FIRSTBLOOD_2x2', 'SR_6x6': 'SR_6x6', 'URF_5x5': 'URF_5x5', 'ONEFORALL_MIRRORMODE_5x5': 'ONEFORALL_MIRRORMODE_5x5', 'BOT_URF_5x5': 'BOT_URF_5x5', 'NIGHTMARE_BOT_5x5_RANK1': 'NIGHTMARE_BOT_5x5_RANK1', 'NIGHTMARE_BOT_5x5_RANK2': 'NIGHTMARE_BOT_5x5_RANK2', 'NIGHTMARE_BOT_5x5_RANK5': 'NIGHTMARE_BOT_5x5_RANK5', 'ASCENSION_5x5': 'ASCENSION_5x5', 'HEXAKILL': 'HEXAKILL', 'BILGEWATER_ARAM_5x5': 'BILGEWATER_ARAM_5x5', 'KING_PORO_5x5': 'KING_PORO_5x5', 'COUNTER_PICK': 'COUNTER_PICK', 'BILGEWATER_5x5': 'BILGEWATER_5x5', 'TEAM_BUILDER_DRAFT_UNRANKED_5x5': 'TEAM_BUILDER_DRAFT_UNRANKED_5x5', 'TEAM_BUILDER_DRAFT_RANKED_5x5': 'TEAM_BUILDER_DRAFT_RANKED_5x5'}
queueTypeByNameId = {"CUSTOM": {"id": 0, "name": "Custom"},"NORMAL_3x3": {"id": 8, "name": "Normal 3v3"},"NORMAL_5x5_BLIND": {"id": 2, "name": "Normal 5v5 Blind Pick"},"NORMAL_5x5_DRAFT": {"id": 14, "name": "Normal 5v5 Draft Pick"},"RANKED_SOLO_5x5": {"id": 4, "name": "Ranked Solo 5v5"},"RANKED_PREMADE_5x5": {"id": 6, "name": "Ranked Premade 5v5"},"RANKED_PREMADE_3x3": {"id": 9, "name": "Ranked Premade 3v3"},"RANKED_TEAM_3x3": {"id": 41, "name": "Ranked Team 3v3"},"RANKED_TEAM_5x5": {"id": 42, "name": "Ranked Team 5v5"},"ODIN_5x5_BLIND": {"id": 16, "name": "Dominion 5v5 Blind Pick"},"ODIN_5x5_DRAFT": {"id": 17, "name": "Dominion 5v5 Draft Pick"},"BOT_5x5": {"id": 7, "name": "Historical Summoner's Rift Coop vs AI"},"BOT_ODIN_5x5": {"id": 25, "name": "Dominion Coop vs AI"},"BOT_5x5_INTRO": {"id": 31, "name": "Summoner's Rift Coop vs AI Intro Bot"},"BOT_5x5_BEGINNER": {"id": 32, "name": "Summoner's Rift Coop vs AI Beginner Bot"},"BOT_5x5_INTERMEDIATE": {"id": 33, "name": "Historical Summoner's Rift Coop vs AI Intermediate Bot"},"BOT_TT_3x3": {"id": 52, "name": "Twisted Treeline Coop vs AI"},"GROUP_FINDER_5x5": {"id": 61, "name": "Team Builder"},"ARAM_5x5": {"id": 65, "name": "ARAM"},"ONEFORALL_5x5": {"id": 70, "name": "One for All"},"FIRSTBLOOD_1x1": {"id": 72, "name": "Snowdown Showdown 1v1"},"FIRSTBLOOD_2x2": {"id": 73, "name": "Snowdown Showdown 2v2"},"SR_6x6": {"id": 75, "name": "Summoner's Rift 6x6 Hexakill"},"URF_5x5": {"id": 76, "name": "Ultra Rapid Fire"},"ONEFORALL_MIRRORMODE_5x5": {"id": 78, "name": "One for All (Mirror mode)"},"BOT_URF_5x5": {"id": 83, "name": "Ultra Rapid Fire played against AI"},"NIGHTMARE_BOT_5x5_RANK1": {"id": 91, "name": "Doom Bots Rank 1"},"NIGHTMARE_BOT_5x5_RANK2": {"id": 92, "name": "Doom Bots Rank 2"},"NIGHTMARE_BOT_5x5_RANK5": {"id": 93, "name": "Doom Bots Rank 5"},"ASCENSION_5x5": {"id": 96, "name": "Ascension"},"EXAKILL": {"id": 98, "name": "Twisted Treeline 6x6 Hexakill"},"BILGEWATER_ARAM_5x5": {"id": 100, "name": "Butcher's Bridge"},"KING_PORO_5x5": {"id": 300, "name": "King Poro"},"COUNTER_PICK": {"id": 310, "name": "Nemesis"},"BILGEWATER_5x5": {"id": 313, "name": "Black Market Brawlers"},"SIEGE": {"id": 315, "name": "Nexus Siege"},"DEFINITELY_NOT_DOMINION_5x5": {"id": 317, "name": "Definitely Not Dominion"},"TEAM_BUILDER_DRAFT_UNRANKED_5x5": {"id": 400, "name": "Normal 5v5 Draft Pick"},"TEAM_BUILDER_DRAFT_RANKED_5x5": {"id": 410, "name": "Ranked 5v5 Draft Pick"}}
queueTypeById = {"0": {"nameId": "CUSTOM", "name": "Custom"},"8": {"nameId": "NORMAL_3x3", "name": "Normal 3v3"},"2": {"nameId": "NORMAL_5x5_BLIND", "name": "Normal 5v5 Blind Pick"},"14": {"nameId": "NORMAL_5x5_DRAFT", "name": "Normal 5v5 Draft Pick"},"4": {"nameId": "RANKED_SOLO_5x5", "name": "Ranked Solo 5v5"},"6": {"nameId": "RANKED_PREMADE_5x5", "name": "Ranked Premade 5v5"},"9": {"nameId": "RANKED_PREMADE_3x3", "name": "Ranked Premade 3v3"},"41": {"nameId": "RANKED_TEAM_3x3", "name": "Ranked Team 3v3"},"42": {"nameId": "RANKED_TEAM_5x5", "name": "Ranked Team 5v5"},"16": {"nameId": "ODIN_5x5_BLIND", "name": "Dominion 5v5 Blind Pick"},"17": {"nameId": "ODIN_5x5_DRAFT", "name": "Dominion 5v5 Draft Pick"},"7": {"nameId": "BOT_5x5", "name": "Historical Summoner's Rift Coop vs AI"},"25": {"nameId": "BOT_ODIN_5x5", "name": "Dominion Coop vs AI"},"31": {"nameId": "BOT_5x5_INTRO", "name": "Summoner's Rift Coop vs AI Intro Bot"},"32": {"nameId": "BOT_5x5_BEGINNER", "name": "Summoner's Rift Coop vs AI Beginner Bot"},"33": {"nameId": "BOT_5x5_INTERMEDIATE", "name": "Historical Summoner's Rift Coop vs AI Intermediate Bot"},"52": {"nameId": "BOT_TT_3x3", "name": "Twisted Treeline Coop vs AI"},"61": {"nameId": "GROUP_FINDER_5x5", "name": "Team Builder"},"65": {"nameId": "ARAM_5x5", "name": "ARAM"},"70": {"nameId": "ONEFORALL_5x5", "name": "One for All"},"72": {"nameId": "FIRSTBLOOD_1x1", "name": "Snowdown Showdown 1v1"},"73": {"nameId": "FIRSTBLOOD_2x2", "name": "Snowdown Showdown 2v2"},"75": {"nameId": "SR_6x6", "name": "Summoner's Rift 6x6 Hexakill"},"76": {"nameId": "URF_5x5", "name": "Ultra Rapid Fire"},"78": {"nameId": "ONEFORALL_MIRRORMODE_5x5", "name": "One for All (Mirror mode)"},"83": {"nameId": "BOT_URF_5x5", "name": "Ultra Rapid Fire played against AI"},"91": {"nameId": "NIGHTMARE_BOT_5x5_RANK1", "name": "Doom Bots Rank 1"},"92": {"nameId": "NIGHTMARE_BOT_5x5_RANK2", "name": "Doom Bots Rank 2"},"93": {"nameId": "NIGHTMARE_BOT_5x5_RANK5", "name": "Doom Bots Rank 5"},"96": {"nameId": "ASCENSION_5x5", "name": "Ascension"},"98": {"nameId": "EXAKILL", "name": "Twisted Treeline 6x6 Hexakill"},"100": {"nameId": "BILGEWATER_ARAM_5x5", "name": "Butcher's Bridge"},"300": {"nameId": "KING_PORO_5x5", "name": "King Poro"},"310": {"nameId": "COUNTER_PICK", "name": "Nemesis"},"313": {"nameId": "BILGEWATER_5x5", "name": "Black Market Brawlers"},"315": {"nameId": "IEGE", "name": "Nexus Siege"},"317": {"nameId": "DEFINITELY_NOT_DOMINION_5x5", "name": "Definitely Not Dominion"},"400": {"nameId": "TEAM_BUILDER_DRAFT_UNRANKED_5x5", "name": "Normal 5v5 Draft Pick"},"410": {"nameId": "TEAM_BUILDER_DRAFT_RANKED_5x5", "name": "Ranked 5v5 Draft Pick"}}

matchType = {'CUSTOM_GAME': 'Custom', 'MATCHED_GAME': 'Matched', 'TUTORIAL_GAME': 'Tutorial'}

subType = {"NONE": "Custom","NORMAL": "Summoner's","NORMAL_3x3": "Twisted","ODIN_UNRANKED": "Dominion/Crystal","ARAM_UNRANKED_5x5": "ARAM","BOT": "Summoner's","BOT_3x3": "Twisted","ANKED_SOLO_5x5": "Summoner's","RANKED_TEAM_3x3": "Twisted","RANKED_TEAM_5x5": "Summoner's","ONEFORALL_5x5": "One","FIRSTBLOOD_1x1": "Snowdown","FIRSTBLOOD_2x2": "Snowdown","SR_6x6": "Summoner's","CAP_5x5": "Team","URF": "Ultra","URF_BOT": "Ultra","NIGHTMARE_BOT": "Summoner's","ASCENSION": "Ascension","HEXAKILL": "Twisted","KING_PORO": "King","COUNTER_PICK": "Nemesis","BILGEWATER": "Black","SIEGE": "Nexus"}

playerStatSummaryType = {"Unranked": "Summoner's","Unranked3x3": "Twisted","OdinUnranked": "Dominion/Crystal","AramUnranked5x5": "ARAM","CoopVsAI": "Summoner's","CoopVsAI3x3": "Twisted","RankedSolo5x5": "Summoner's","RankedTeam3x3": "Twisted","RankedTeam5x5": "Summoner's","OneForAll5x5": "One","FirstBlood1x1": "Snowdown","FirstBlood2x2": "Snowdown","SummonersRift6x6": "Summoner's","CAP5x5": "Team","URF": "Ultra","URFBots": "Ultra","NightmareBot": "Summoner's","Ascension": "Ascension","Hexakill": "Twisted","KingPoro": "King","CounterPick": "Nemesis","Bilgewater": "Black","Siege": "Nexus"}

season = {'PRESEASON3,': 'PRESEASON3,', 'SEASON3,': 'SEASON3,', 'PRESEASON2014,': 'PRESEASON2014,', 'SEASON2014,': 'SEASON2014,', 'PRESEASON2015,': 'PRESEASON2015,', 'SEASON2015,': 'SEASON2015,', 'PRESEASON2016,': 'PRESEASON2016,', 'SEASON2016': 'SEASON2016'}
highestAchievedSeasonTier = {'CHALLENGER,': 'CHALLENGER,', 'MASTER,': 'MASTER,', 'DIAMOND,': 'DIAMOND,', 'PLATINUM,': 'PLATINUM,', 'GOLD,': 'GOLD,', 'SILVER,': 'SILVER,', 'BRONZE,': 'BRONZE,', 'UNRANKED': 'UNRANKED'}




